### ISSUE TITLE
Can't load settings screen

### ISSUE THREAD

**Issue by KatieMFritz** [superbigco/craft-reports#1]
When I go to the plugin settings URI, I get the following error:

`Key "someAttribute" in object with ArrayAccess of class "superbig\reports\models\Settings" does not exist.`

Some of the stack trace:
![Screen Shot 2019-07-30 at 3 43 05 PM](https://user-images.githubusercontent.com/7085184/62159900-c17b1c00-b2e0-11e9-879d-5d4e579ab9d3.png)

Using Postgres. Let me know if you need any more info - or if I was supposed to configure something else first and this is expected behavior.

Thanks!

**Comment by sjelfull** [comment]
Thanks for reporting. This is a bug. There is no settings screen because the settings is added per report / target, so I shall remove this.

**Comment by sjelfull** [comment]
This should be fixed in 1.0.6
