### ISSUE TITLE
Postgres - null value in column "id" violates not-null constraint

### ISSUE THREAD

**Issue by john-henry** [superbigco/craft-reports#15]
**Describe the bug**
Saving a new report generates an error. We are using Postgres

> Integrity constraint violation – yii\db\IntegrityException
> SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "id" violates not-null constraint

**Additional context**

- Craft version:  3.3.20.1
- Reports: 1.0.7

**Comment by sjelfull** [comment]
Thanks for reporting. There is a few Postgres incompatible queries in the plugin. Will have a fix out soon.
