### ISSUE TITLE
Issue with user permissions

### ISSUE THREAD

**Issue by pixelmachine** [superbigco/craft-reports#3]
I've setup a simple report, which works correctly for my user.

1. Enable a limited user to only Run and Export from craft-reports.
2. Login as the user
3a. Reports is accessible, Export works, Run does not work and redirects to the index. 
3b. There is a still a link on the report name linking to a page that is inaccessible.

Obviously Run should work and I think there should be no link on the report name.

**Comment by sjelfull** [comment]
Thanks, I'll release a fix for this very soon.

**Comment by mark-adigital** [comment]
Hi - I'm seeing an issue with permissions too, however in my case I can't even access the reports section of the CMS with my limited user, regardless of which permissions I grant them.

**Comment by sjelfull** [comment]
No surprise there - after looking into this, I noticed it had some glaring problems with the way it is setup.

I'm currently reworking it. Hope to cut a release with this + a few other fixes early next week.

**Comment by mark-adigital** [comment]
Ok, thanks for the speedy response!

**Comment by mark-adigital** [comment]
Hi - just wondered if there was any update on when a new release addressing this may be out? Thanks.

**Comment by sjelfull** [comment]
Sorry about the delay on this. I'll be tagging a new release today that should fix this. Note that you need to set the permissions again, as I have simplified them somewhat and changed names.

Let me know if all is good after the update.

**Comment by mark-adigital** [comment]
No worries, thanks for the release! All looks good, though I did spot after running a report that there's a breadcrumb link to edit it which the user may not have access to do, in which case they see an unauthorised error - not a dealbreaker though.

**Comment by sjelfull** [comment]
Good to hear that. The link will be fixed in the next release.
