### ISSUE TITLE
Unable to make Report Target > Email Subject dynamic

### ISSUE THREAD

**Issue by zackspear** [superbigco/craft-reports#5]
Thanks so much for an extremely helpful plugin.

Unfortunately when setting a Report Target's Email Subject field to be something dynamic to prevent email clients from threading emails like:
```
Monthly Order Report // {now|date_modify('-1 month')|date} - {now|date}
```
or even
```
Monthly Order Report // {{ now|date_modify('-1 month')|date }} - {{ now|date }}
```
the email subject is plaintext exactly as written. The Twig handles aren't executed.

**Steps to reproduce the behavior:**
1. Copy and paste the above snippets
2. Go to a report target entry page
3. Paste snippet into "Subject" field.
4. Run Target
5. Check email, see plaintext subject

**Expected behavior**
Email subject should be "Monthly Order Report // Aug 11, 2019, 4:44:58 PM - Sep 11, 2019, 4:44:58 PM"

**Screenshot of inbox**
![Screenshot 2019-09-11 17 24 58](https://user-images.githubusercontent.com/2531682/64744572-37b29700-d4b9-11e9-8e46-9df934a870c8.png)

- Craft CMS 3.3.1.2
- Reports 1.0.6

**Comment by sjelfull** [comment]
Your right, its not currently parsed. I'll have a release out within the next week that fixes this.

**Comment by sjelfull** [comment]
1.0.7 was released this week which fixes this.
